name: Self-test
on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
      - main
jobs:
  test-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: version
        uses: pulumi/provider-version-action@v1

      - run: mkdir -p sdk
      - run: echo "module github.com/pulumi/publish-go-sdk-action/self-test" > sdk/go.mod

      - uses: ./
        name: Publish Go SDK back to own repository
        with:
          repository: ${{ github.repository }}
          base-ref: ${{ github.sha }}
          source: sdk
          path: self-test
          version: ${{ steps.version.outputs.version }}
          additive: false
