name: Self-test
on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
      - main
    tags:
      - "v*"
jobs:
  test-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: mkdir -p sdk
      - run: echo "module github.com/pulumi/publish-go-sdk-action/self-test" > sdk/go.mod
      - run: echo "package main" > sdk/main.go
      - run: echo "README" > sdk/README.md

      - uses: ./
        name: Publish Go SDK back to own repository
        with:
          repository: ${{ github.repository }}
          base-ref: ${{ github.sha }}
          source: sdk
          path: self-test
          version: 1.0.0-alpha.${{ github.run_number }}
          additive: false
          files: |
            go.mod
            **/*.go

      - name: Clean up test tag
        run: git push origin --delete "self-test/v1.0.0-alpha.${{ github.run_number }}"

  test-publish-v2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: mkdir -p sdk
      - run: echo "module github.com/pulumi/publish-go-sdk-action/self-test/v2" > sdk/go.mod

      - uses: ./
        name: Publish Go SDK back to own repository
        with:
          repository: ${{ github.repository }}
          base-ref: ${{ github.sha }}
          source: sdk
          path: self-test
          version: 2.0.0-alpha.${{ github.run_number }}
          additive: false

      - uses: ./
        name: Check running twice doesn't fail
        with:
          repository: ${{ github.repository }}
          base-ref: ${{ github.sha }}
          source: sdk
          path: self-test
          version: 2.0.0-alpha.${{ github.run_number }}
          additive: false

      - name: Clean up test tag
        run: git push origin --delete "self-test/v2.0.0-alpha.${{ github.run_number }}"
